services:
  backend:
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null 127.0.0.1:5000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
  frontend:
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null 127.0.0.1/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
